#!/usr/bin/env python

#usage:  db collection arg1:v1 arg2:v2 ... arga argb


import os, sys, sys, time, csv, datetime, re, pymongo, string
from pymongo import MongoClient
client = MongoClient()

args = sys.argv

args.pop(0)
db = args.pop(0)
coll = args.pop(0)
coll = client[db][coll]

query = {}
cols = []

for a in args:
    m = re.match('(\w+):(\w+)', a)
    if m:
       (k,v) = m.groups()
       query[k] = v
    else:
	cols.append(a)

for row in coll.find(query):
    row = [str(row[c]) for c in cols]
    print " ".join(row)
